# Generated by Django 4.2 on 2023-04-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_prod', models.CharField(max_length=50)),
                ('name_prod2', models.CharField(max_length=50)),
                ('text_prod', models.TextField(max_length=200)),
                ('price_prod', models.FloatField()),
                ('img_prod', models.ImageField(default='produtos/sem_imagem.jpg', upload_to='prod/%Y/%m/%d/')),
                ('category', models.CharField(choices=[('J', 'Jogo'), ('M', 'Mouse'), ('T', 'Teclado'), ('C', 'Computadore'), ('CON', 'Console'), ('M', 'Monitore'), ('P', 'Peça')], max_length=12)),
            ],
        ),
    ]
