# Generated by Django 4.2 on 2023-04-13 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_prod', models.CharField(max_length=50)),
                ('texto_prod', models.TextField(max_length=200)),
                ('preco_prod', models.FloatField()),
            ],
        ),
    ]
