# Generated by Django 4.2 on 2023-04-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='img_prod',
            field=models.ImageField(default='produtos/sem_imagem.jpg', upload_to='media/prod/% Y/% m/% d/'),
        ),
    ]
