# Generated by Django 4.2 on 2023-04-16 15:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prod',
            name='name_prod2',
        ),
        migrations.AddField(
            model_name='prod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
