# Generated by Django 4.2 on 2023-04-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce_app', '0002_remove_prod_name_prod2_prod_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='prod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
